### ISSUE TITLE
Uncaught Error on google.accounts.id.renderButton

### ISSUE THREAD

**Issue by AlmasF** [eduardova/vue-google-identity-login-btn#3]
On InitGoogleButton when button should be displayed throws an Uncaught Error in 
![image](https://github.com/eduardova/vue-google-identity-login-btn/assets/55618258/97040c76-7d92-4fb4-8044-827f70499cf5)
this part

**Comment by eduardova** [comment]
Hi, this is a known issue, you can manually specify the width property, you can see more details here:

https://github.com/eduardova/vue-google-identity-login-btn/pull/1#issuecomment-1656851013
